image: node:18.19

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - npm install --legacy-peer-deps
          - npm install -g @angular/cli
          - export NODE_OPTIONS=--openssl-legacy-provider; ng build --configuration=uat
          - cd dist/guard-walk
          - pipe: atlassian/aws-s3-deploy:0.2.4
            variables:
                AWS_ACCESS_KEY_ID: 'AKIA6ODUZFEVQZKBZCIY'
                AWS_SECRET_ACCESS_KEY: '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'
                AWS_DEFAULT_REGION: 'ap-southeast-1'
                S3_BUCKET: 'training.web'
                LOCAL_PATH: '$(pwd)'
          - pipe: docker://rudijs/aws-cloudfront-create-invalidation:1.0.2
            variables:
              AWS_ACCESS_KEY_ID: 'AKIA6ODUZFEVQZKBZCIY'
              AWS_SECRET_ACCESS_KEY: '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'
              DISTRIBUTION_ID: 'E2XOF02H1JB6Q9'
